# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hearText.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# Import the Gtts module for text  
# to speech conversion 
from gtts import gTTS 

# import Os module to start the audio file
import os 
import sys

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):

    def loadtext(self):
        f = open("test.txt", "r")
        s=(f.read())

        p = self.plainTextEdit.appendPlainText(s)
        print(p)

    
    def listen(self):
        s=self.plainTextEdit.toPlainText()   

        language = 'en'
        myobj = gTTS(text= s, lang=language, slow=False) 
        myobj.save("output.mp3") 

        # Play the converted file 
        os.system("start output.mp3") 

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(50, 120, 551, 241))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setStyleSheet("background-color: qlineargradient(\
            spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 0, 0, 0), stop:1 \
            rgba(255, 255, 255, 255));color: rgb(87, 255, 208);")
        self.plainTextEdit.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.plainTextEdit.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.plainTextEdit.setObjectName("plainTextEdit")
        
        #BACKGROUND LABEL
        self.background_label = QtWidgets.QLabel(self.centralwidget)
        self.background_label.setGeometry(QtCore.QRect(0, 0, 641, 471))
        self.background_label.setText("")
        self.background_label.setPixmap(QtGui.QPixmap("background.jpg"))
        self.background_label.setScaledContents(True)
        self.background_label.setObjectName("background_label")
        
        #HEADER FRAME
        self.header_frame = QtWidgets.QFrame(self.centralwidget)
        self.header_frame.setGeometry(QtCore.QRect(10, 10, 621, 80))
        self.header_frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_frame.setObjectName("header_frame")
        
        #HEADER LABEL (HEAR YOUR TEXT)
        self.hear_label = QtWidgets.QLabel(self.header_frame)
        self.hear_label.setGeometry(QtCore.QRect(130, 30, 411, 21))
        font = QtGui.QFont()
        font.setFamily("Gunship Expanded")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.hear_label.setFont(font)
        self.hear_label.setStyleSheet("color: rgb(87, 255, 208);")
        self.hear_label.setObjectName("hear_label")

        #ENTER YOUR TEXT BELOW LABEL
        self.enter_text_label = QtWidgets.QLabel(self.centralwidget)
        self.enter_text_label.setGeometry(QtCore.QRect(150, 100, 371, 21))
        font = QtGui.QFont()
        font.setFamily("Gunship Expanded")
        font.setPointSize(15)
        self.enter_text_label.setFont(font)
        self.enter_text_label.setStyleSheet("color: rgb(87, 255, 208);")
        self.enter_text_label.setObjectName("enter_text_label")
        
        
        #LISTEN BUTTON
        self.listen_btn = QtWidgets.QPushButton(self.centralwidget)
        self.listen_btn.setGeometry(QtCore.QRect(50, 380, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Gunship Expanded")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.listen_btn.setFont(font)
        self.listen_btn.setStyleSheet("background-color: qlineargradient(spread:pad,\
         x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 255));")
        self.listen_btn.setObjectName("listen_btn")
        self.listen_btn.clicked.connect(self.listen)
        
        
        #CLEAR BUTTON
        self.clear_btn = QtWidgets.QPushButton(self.centralwidget)
        self.clear_btn.setGeometry(QtCore.QRect(240, 380, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Gunship Expanded")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.clear_btn.setFont(font)
        self.clear_btn.setStyleSheet("background-color: qlineargradient(spread:pad,\
            x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 255));")
        self.clear_btn.setObjectName("clear_btn")
        self.clear_btn.clicked.connect(lambda:self.plainTextEdit.clear())


        self.load_btn = QtWidgets.QPushButton(self.centralwidget)
        self.load_btn.setGeometry(QtCore.QRect(240, 420, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Gunship Expanded")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.load_btn.setFont(font)
        self.load_btn.setStyleSheet("background-color: qlineargradient(spread:pad,\
            x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 255));")
        self.load_btn.setObjectName("load_btn")
        self.load_btn.clicked.connect(self.loadtext)

        #EXIT BUTTON
        self.exit_btn = QtWidgets.QPushButton(self.centralwidget)
        self.exit_btn.setGeometry(QtCore.QRect(430, 380, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Gunship Expanded")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.exit_btn.setFont(font)
        self.exit_btn.setStyleSheet("background-color: qlineargradient(spread:pad, \
            x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 255));")
        self.exit_btn.setObjectName("exit_btn")
        self.exit_btn.clicked.connect(lambda:sys.exit())
        
        self.background_label.raise_()
        self.plainTextEdit.raise_()
        self.header_frame.raise_()
        self.listen_btn.raise_()
        self.enter_text_label.raise_()
        self.clear_btn.raise_()
        self.load_btn.raise_()
        self.exit_btn.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "HEAR YOUR TEXT APP"))
        self.hear_label.setText(_translate("MainWindow", "HEAR YOUR TEXT"))
        self.listen_btn.setText(_translate("MainWindow", "Listen"))
        self.enter_text_label.setText(_translate("MainWindow", "Enter Text Below:"))
        self.clear_btn.setText(_translate("MainWindow", "CLEAR"))
        self.load_btn.setText(_translate("MainWindow", "LOAD"))
        self.exit_btn.setText(_translate("MainWindow", "EXIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
